version: "3"
services:

    nginx:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
       
    node-app:
        build: .
        env_file: 
            - ./.env
    
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes: 
            - mongo-db:/data/db

volumes: 
    mongo-db: